config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "about", to: "pages#about"
  get "legals", to: "pages#legal"
  get "realisations", to: "pages#realisation"
  get "singularity", to: "pages#singularity"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def legal
  end
  def realisation
  end
  def singularity
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tetraktys Concept Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%=render "/shared/navbar" %>
    <% if current_page?(root_path) %>
      <%= render "/shared/banner_root" %>
    <% end %>
    <%= yield %>
    <%= render "/shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="sing-TCM">

  <h2>Croissance & Innovation</h2>

  <div class='about-card'>
    <%= image_tag 'rhphoto.png', class: "avatar-large"%>
    <p>Tetraktys Concept Management est noté « Excellent » dans la catégorie « Restructuring & entreprises en difficulté - Chief Restructuring Officer » par le Magazine Décideurs dans son édition 2020-2021 du Guide « Stratégie, Réorganisation & Restructuration ».</p>

    <a href="assets/TCM_mag_dec.pdf" target="_blank" class='btn btn-TCM vw-10'>voir article</a>

  </div>


  <h3>Les dix points de la Tetraktys représentent chacun une fonction ou une mission de l’entreprise au sens large.</h3>
  <div class='tetra-TCM-cont'>
    <%= image_tag 'tetraktys-sing.jpg', class: "TCM-tetra"%>
    <div class='tetra-cards-cont'>
      <div class="tetra-card blue ">Direction Générale</div>
      <div class="tetra-card blue ">Crise et transformation</div>
      <div class="tetra-card blue ">Sécurité</div>
      <div class="tetra-card gray ">Management</div>
      <div class="tetra-card gray ">Finance</div>
      <div class="tetra-card gray ">Capital humain</div>
      <div class="tetra-card gray ">Stratégie de marque</div>
      <div class="tetra-card gray ">Communication</div>
      <div class="tetra-card gray ">Systèmes d’information</div>
      <div></div>
      <div class="tetra-card yellow ">Innovation</div>
    </div>
  </div>


  <p> Bien maîtrisés, chacun de ces points est, dans notre vision, un « asset » de l’entreprise et participe à la fois au bon fonctionnement collectif, au bien être au travail des salariés et à la création de valeur actionnariale. <br>
  L’ensemble des dix points décrivant l’entreprise doivent se lire et être mis en œuvre dans l’ensemble plus global des valeurs exprimées dans les 17 Obligations de Développement Durable de l’ONU. Ces valeurs (tout comme la qualité de vie au travail) sous-tendent toutes les actions de l’entreprise et déterminent non seulement sa RSE, mais son existence sociale.</p>

  <p>Nos interventions sont caractérisées par la mise en place de solutions structurelles (M&A, Restructuring notamment) optimisant les intérêts de toutes les parties dans des environnements complexes, voire financièrement très tendus (mandats ad hoc avec deadline des créanciers).</p>

</div>

app/views/pages/home.html.erb
<div class="container">


  <div class="d-flex justify-content-around">

    <div class='home-cards interim-color'>
      <h3>Intérim management</h3>
      <ul>
        <div class='info-container'>
          <div>
            <i class="fa-solid fa-star"></i>
            <p>Direction Générale</p>
          </div>
          <div>
            <i class="fa-solid fa-people-group"></i>
            <p>Direction Innovation, Direction Financière, Secrétariat Général Groupe</p>
          </div>
          <div>
            <i class="fa-solid fa-globe"></i>
            <p>Pilotage de deals complexes nationaux ou internationaux</p>
          </div>
        </div>
      </ul>
    </div>

    <div class='home-cards conseil-color'>
      <h3>Conseil en stratégie</h3>
      <ul>
        <div class='info-container'>
          <div>
            <i class="fa-solid fa-lightbulb"></i>
            <p>Innovation</p>
          </div>
          <div>
            <i class="fa-solid fa-bolt"></i>
            <p>Synergies</p>
          </div>
          <div>
            <i class="fa-solid fa-people-arrows-left-right"></i>
            <p>Diplomatie d’Entreprise</p>
          </div>
          <div>
            <i class="fa-solid fa-laptop"></i>
            <p>Digitalisation</p>
          </div>
        </div>
      </ul>
    </div>

    <div class='home-cards accompagnement-color'>
      <h3>Accompagnement</h3>
      <ul>
        <div class='info-container'>
          <div>
            <i class="fa-solid fa-calendar-check"></i>
            <p>Animation de séminaires</p>
          </div>
          <div>
            <i class="fa-solid fa-business-time"></i>
            <p>Coaching humaniste pour dirigeant (Président, Directeur Général, CFO…)</p>
          </div>
        </div>
      </ul>
    </div>

  </div>
</div>

app/views/pages/legal.html.erb
<div class="legal-TCM">

  <h2>Mentions légales</h2>

  <h4>Conditions générales d'utilisation</h4>
  <p>Bienvenue sur le site internet www.tetraktys-cm.com. En vous connectant ou en utilisant notre site internet, vous reconnaissez avoir lu, compris, et accepté, sans limitation ni réserve, les présentes conditions générales d'utilisation.</p>

  <h4>Identité</h4>
  <p>
    Société éditrice du site internet, ci-après la « Société » :
    Dénomination : Tetraktys Concept Management <br>
    Adresse : 12 allée des plumassiers 77600 Bussy Saint Georges <br>
    Forme juridique : SASU Société par actions simplifiée à associé unique <br>
    Mail : rudolph.hidalgo@tetraktys-cm.com <br>
    Numéro RCS : 821 647 591 R.C.S. PARIS <br>
    Nom du responsable de la publication : Monsieur Rudolph HIDALGO <br>
  </p>

  <h4>Conception technique et développement du site internet</h4>
  <p>TO BE COMPLETED</p>

  <h4>L'hébergement du site internet est assuré par</h4>
  <p>TO BE COMPLETED</p>

  <h4>Liens hypertextes</h4>
  <h5>Activation des liens</h5>
  <p>La société décline formellement toute responsabilité quant aux contenus des sites vers lesquels elle offre des liens. Ces liens sont proposés aux utilisateurs de ce site internet. La décision d'activer les liens appartient exclusivement aux utilisateurs du site internet. La société peut modifier ou supprimer un lien sur son site internet à tout moment.</p>
  <h5>Autorisation des liens</h5>
  <p>
    Si vous souhaitez créer un lien hypertexte avec ce site internet, vous devez obtenir l'autorisation écrite et préalable de la direction de la société. <br>
    Les liens hypertextes établis en direction d'autres sites à partir de www.tetraktys-cm.com ne sauraient, en aucun cas, engager la responsabilité de la société. <br>
    Tout lien ou framing de ce site est strictement interdit et en conséquence, aucun élément figurant sur une page du site internet de la société ne peut être partiellement ou totalement, diffusé, transféré ou inséré sur un autre site internet, ni servir à créer des produits dérivés, sauf autorisation expresse de la direction de la société.
  </p>

  <h4>Droits de propriété intellectuelle et droits d'auteurs</h4>
  <p>
  La reproduction ou représentation, intégrale ou partielle, des pages, des données et de toute autre élément constitutif au site, par quelque procédé ou support que ce soit, est interdite et constitue, sans autorisation de l'éditeur, une contrefaçon. <br>
  Tous les éléments du site internet www.tetraktys-cm.com sont protégés par les droits de propriété intellectuelle. La reproduction et l'utilisation de tous documents publiés sur ce site sont exclusivement autorisés à des fins personnelles et privées et moyennant mention de la source. Toute reproduction, utilisation ou diffusion de copies réalisées à d'autres fins est expressément interdite et sanctionnée pénalement. <br>
  Le nom « nom de la société » est une marque déposée. Toute utilisation frauduleuse constitue une contrefaçon et est passible des sanctions pénales prévues aux articles L.716-1 et suivants du Code de la propriété intellectuelle.
  </p>

  <h4>Mises en garde</h4>
  <p>
    Les informations et recommandations disponibles sur ce site internet (« Informations ») sont proposées de bonne foi. Elles sont censées être correctes au moment où elles sont publiées sur le site. Toutefois, la société ne garantit pas le caractère exhaustif et l'exactitude de ces Informations. Vous assumez pleinement les risques liés au crédit que vous leur accordez. Ces Informations vous sont fournies à la condition que vous ou toute autre personne qui les recevez puissiez déterminer leur intérêt pour un objectif précis avant de les utiliser. En aucun cas, la société ne sera responsable des dommages susceptibles de résulter du crédit accordé à ces Informations ou de leur utilisation. Ces Informations ne doivent pas être considérées comme des recommandations pour l'utilisation d'informations, de produits, de procédures, d'équipements ou de formulations qui seraient en contradiction avec un brevet, un copyright ou une marque déposée. La société décline toute responsabilité, expresse ou implicite, si l'utilisation de ces Informations venait à contrevenir à un brevet, un copyright ou une marque déposée. <br>
    La société assure une actualisation régulière du site, mais décline toute responsabilité quant aux inexactitudes, erreurs ou omissions. <br>
    La société ne pourra être tenu responsable pour quelque dommage que ce soit résultant d'une information contenue sur ce site. <br>
    La société se réserve le droit de modifier à tout moment et sans préavis les présentes informations. De même, la société se réserve le droit de suspendre, d'interrompre ou d'annuler l'accès à tout ou partie du site en cas d'incidents techniques ou en cas de force majeure. <br>
    Les informations diffusées sur ce site ne sauraient en aucun cas être interprétées comme un démarchage ou une incitation à acquérir des valeurs mobilières de la société.
  </p>

  <h4>Droit applicable</h4>
  <p>Le site Internet et ses conditions d'accès et d'utilisation sont régis par le droit français. Tout différend relatif au dit site Internet sera soumis à la compétence exclusive des Tribunaux de Paris.</p>

  <h4>Mises à jour des conditions d'utilisation du site internet et loi applicable</h4>
  <p>La Société peut procéder à la mise à jour de ces conditions d'utilisation à tout moment. En conséquence, vous êtes invités à vous référer régulièrement aux dernières conditions d'utilisation en vigueur. Ces conditions d'utilisation sont soumises au droit applicable et relèvent de la compétence des tribunaux compétents.</p>

  <h4>Informations techniques</h4>
  <p>Il est rappelé que le secret des correspondances n'est pas garanti sur le réseau et qu'il appartient à chaque utilisateur d'Internet de prendre toutes les mesures appropriées de façon à protéger ses propres données et/ou logiciels de la contamination d'éventuels virus circulant sur Internet.</p>

</div>

app/views/pages/realisation.html.erb
<div class="real-TCM">

  <h2>Réalisations principales de TCM au cours des dernières années</h2>

  <div class="img-cont">
    <%= image_tag 'Hamleys.jpg', class: "img"%>
  </div>
  <h3>Acquisition en 2012 puis la cession en 2016 de la marque de jouets iconique anglaise</h3>
  <div class="real-videos">
    <div class="video-card">
      <i class="fa-solid fa-money-bill"></i>
      <p>L’acquisition, ou le grand saut stratégique</p>

    </div>
    <div class="video-card">
      <i class="fa-solid fa-truck"></i>
      <p>Optimiser la gestion des franchisés et la Supply Chain</p>

    </div>
    <div class="video-card">
      <i class="fa-solid fa-euro-sign"></i>
      <p>La cession, ou les contraintes de la crise</p>

    </div>

  </div>

  <div class="img-cont">
    <%= image_tag 'FCW1.jpg', class: "img"%>
  </div>
  <h3>Relance de la marque de jouets iconique suisse</h3>
  <div class="real-videos">
    <div class="video-card">
      <i class="fa-solid fa-money-bill-trend-up"></i>
      <p>La relance de Franz Carl Weber</p>

    </div>

  </div>

  <div class="img-cont">
    <%= image_tag 'CIAT.jpg', class: "img"%>
  </div>
  <h3>CIAT (Compagnie Internationale André Trigano) – Les trois phases de la mission (2016 – 2020)</h3>
  <div class="real-videos">
    <div class="video-card">
      <i class="fa-solid fa-file-circle-exclamation"></i>
      <p>Les enjeux du dossier</p>

    </div>
    <div class="video-card">
      <i class="fa-solid fa-1"></i>
      <p>Restructuration financière & conditions de la relance</p>

    </div>
    <div class="video-card">
      <i class="fa-solid fa-2"></i>
      <p>Restructuration industrielle & recentrage</p>

    </div>
    <div class="video-card">
      <i class="fa-solid fa-3"></i>
      <p>Cession dans le contexte Coronavirus</p>

    </div>

  </div>

</div>

app/views/pages/singularity.html.erb
<div class="sing-TCM">
  <h2>Une démarche originale</h2>
  <p>
    Notre démarche originale met l’innovation au coeur de votre Entreprise dans le respect de votre ADN et de vos valeurs. De ce fait, nous ne proposons que du sur-mesure : nous bannissons toute duplication de process ou de solution parce que votre situation est nécessairement singulière.
  </p>
  <div class='sing-card-cont'>
    <div class="sing-card">
      <p>Notre démarche repose d’abord sur <strong>l’écoute, la compréhension et l’analyse de vos besoins</strong>. Ensuite, nous savons trouver rapidement les propositions d’axes de travail adaptés à votre Entreprise et surtout à votre Timing.</p>
      <p>Sur le chemin critique d’une <strong>croissance, durable et profitable, équilibrée au plan humain et au plan financier que nous dessinerons ensemble</strong>, notre valeur ajoutée réside dans notre capacité à réaligner sur un temps commun et pacifié l’ensemble des parties prenantes internes et externes de votre Entreprise. <br> <strong>Les solutions techniques que nous proposerons seront alors aisément mises en place</strong>. Sans ce réalignement préalable, elles risqueraient de ne représenter une solution que sur le très court terme, voire de générer davantage d’entropie.</p>
      <p><strong>Nous mettons au service de cette vision originale et qui fait ses preuves une maîtrise croisée de la stratégie, du Leadership et du management de haut niveau, de l’innovation active et de la finance.</strong></p>
    </div>
    <%= image_tag 'chess.png', class: "sing-img"%>
  </div>

  <h3>L'importance de la formation</h3>
  <div class="sing-videos">
    <div class="video-card">
      <i class="fa-solid fa-graduation-cap"></i>
      <p>Casser le mur de verre par l’apprentissage et la transformation</p>
      <button type="button" class="btn btn-TCM w-40" data-bs-toggle="modal" data-bs-target="#learningModal">
        voir vidéo
      </button>
    </div>
    <div class="video-card">
      <i class="fa-solid fa-arrow-right-arrow-left"></i>
      <p>Acquérir la transversalité par la formation</p>
      <button type="button" class="btn btn-TCM w-40" data-bs-toggle="modal" data-bs-target="#transversModal">
        voir vidéo
      </button>
    </div>
    <div class="video-card">
      <i class="fa-solid fa-signs-post"></i>
      <p>La valeur de la formation : être acteur de son parcours</p>
      <button type="button" class="btn btn-TCM w-40" data-bs-toggle="modal" data-bs-target="#pathModal">
        voir vidéo
      </button>
    </div>
  </div>

  <h3>Un Manager de transition singulier</h3>
  <div class="sing-videos">
    <div class="video-card">
      <i class="fa-solid fa-star"></i>
      <p>Parcours de Rudolph Hidalgo</p>
      <button type="button" class="btn btn-TCM w-40" data-bs-toggle="modal" data-bs-target="#rudolphModal">
        voir vidéo
      </button>
    </div>
    <div class="video-card">
      <i class="fa-solid fa-fire-flame-curved"></i>
      <p>L’apport de la pratique des arts martiaux</p>
      <button type="button" class="btn btn-TCM w-40" data-bs-toggle="modal" data-bs-target="#karateModal">
        voir vidéo
      </button>
    </div>
  </div>

  <div class="modal fade" id="learningModal" tabindex="-1" aria-labelledby="learningModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <iframe class="video-TCM"src="https://youtube.com/embed/7hOAWKHbnoY" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="transversModal" tabindex="-1" aria-labelledby="transversModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <iframe class="video-TCM"src="https://youtube.com/embed/re3ziWwrkSg" gesture="media" allow="encrypted-media" allowfullscreen ></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="pathModal" tabindex="-1" aria-labelledby="pathModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <iframe class="video-TCM"src="https://youtube.com/embed/Qc5PnxysfJw" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="rudolphModal" tabindex="-1" aria-labelledby="rudolphModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <iframe class="video-TCM"src="https://youtube.com/embed/kPUG9ldNj9k" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="karateModal" tabindex="-1" aria-labelledby="karateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <iframe class="video-TCM"src="https://youtube.com/embed/OuyW9wsuKfs" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_banner.html.erb
<div class="banner-TCM">
  <div>
    <p>Cabinet de conseil stratégique exécutant des missions de management de transition, de conseil et d’accompagnement centrées sur l’accélération de croissance et la transformation par l’innovation.</p>
  </div>
  <div>
    <p>Nos interventions nous permettent de mettre en oeuvre notre concept original de management stratégique qui relie et met en synergies toutes les fonctions de l’entreprise en plaçant l’innovation au coeur du réacteur de votre croissance.</p>
  </div>
</div>

app/views/shared/_banner_root.html.erb
<div class="banner-root-TCM">
  <div>
    <p>Cabinet de conseil en stratégie, exécutant des missions de management de transition, de conseil et d’accompagnement centrées sur l’accélération de croissance et la transformation par l’innovation.</p>
  </div>
  <div>
    <p>Nos interventions nous permettent de mettre en oeuvre notre concept original de management stratégique qui relie et met en synergies toutes les fonctions de l’entreprise en plaçant l’innovation au coeur du réacteur de votre croissance.</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-TCM">
  <a href="legals">Mentions légales</a>
  <p>© 2020 - 2022 Tetraktys Concept Management</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-TCM">
  <div class="navbar-TCM-container">
    <%# <img src="assets/TCM-logo-blue.jpg" alt="TCM logo" > %>
    <%= image_tag "TCM-logo-blue.jpg", class: 'TCM-logo-navbar'%>
    <h1 class="me-auto">Tetraktys Concept Management</h1>
    <div class="menu">
      <ul class="list-inline tabs-underlined">
        <li>
          <a href="/" class="tab-underlined <%= "active" if current_page?(root_path)%>"><i class="fa-solid fa-house"></i></a>
        </li>
        <li>
          <a href="realisations" class="tab-underlined <%= "active" if current_page?(realisations_path)%>">Réalisations</a>
        </li>
        <li>
          <a href="singularity" class="tab-underlined <%= "active" if current_page?(singularity_path)%>">Singularités</a>
        </li>
        <li>
          <a href="about" class="tab-underlined <%= "active" if current_page?(about_path)%>">A propos</a>
        </li>
      </ul>
    </div>
  </div>
 </div>